<a href="https://colab.research.google.com/github/VivekMuraleedharanGit/Notebooks/blob/master/Weather_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Weather data set

Data set consisits of time series data with per hour information at perticular Dwe point temparature,Relative Humidity,Wind speed,Visibility,Pressure and condition

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Udemy bootcamp/1. Weather Data.csv')

In [ ]:
data.head()

       Date/Time  Temp_C  ...  Press_kPa               Weather
0  1/1/2012 0:00    -1.8  ...     101.24                   Fog
1  1/1/2012 1:00    -1.8  ...     101.24                   Fog
2  1/1/2012 2:00    -1.8  ...     101.26  Freezing Drizzle,Fog
3  1/1/2012 3:00    -1.5  ...     101.27  Freezing Drizzle,Fog
4  1/1/2012 4:00    -1.5  ...     101.23                   Fog

[5 rows x 8 columns]

In [ ]:
data.shape

(8784, 8)

In [ ]:
data.index

RangeIndex(start=0, stop=8784, step=1)

In [ ]:
data.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

In [ ]:
#weather is categorical feature will see the unique values in that column

data['Weather'].value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Freezing Drizzle,Fog                          6
Snow,Ice Pellets                              6
Snow,Haze                                     5
Freezing Fog                                  4
Moderate Snow                                 4
Freezing Rain,Fog                             4
Snow Showers,Fog                              4
Rain,Snow,Ice Pellets                         4
Thunderstorms,Rain Showers,Fog                3
Thunderstorms,Rain                            3
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Rain Showers,Snow Showers                     2
Moderate Snow,Blowing Snow                    2
Freezing Rain,Haze                            2
Thunderstorms                                 2
Drizzle,Snow                                  2
Freezing Rain,Ice Pellets,Fog                 1
Thunderstorms,Heavy Rain Showers              1
Rain,Snow Grains                              1
Moderate Rain,Fog                             1
Rain Showers,Fog                              1
Thunderstorms,Rain,Fog                        1
Freezing Rain,Snow Grains                     1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Drizzle,Ice Pellets,Fog                       1
Rain,Ice Pellets                              1
Name: Weather, dtype: int64

In [ ]:
#count to check the values in dataset
data.count()

Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

In [ ]:
#Null values in the data set
data.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

In [ ]:
#there is no null values on the dataset

In [ ]:
#1.find all unique"wind speed' values in data

In [ ]:
data.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

In [ ]:
data['Wind Speed_km/h'].nunique()

34

In [ ]:
#2. Find the number of times when the 'Weather is exactly clear'
data.head(2)

       Date/Time  Temp_C  Dew Point Temp_C  ...  Visibility_km  Press_kPa  Weather
0  1/1/2012 0:00    -1.8              -3.9  ...            8.0     101.24      Fog
1  1/1/2012 1:00    -1.8              -3.7  ...            8.0     101.24      Fog

[2 rows x 8 columns]

In [ ]:
data[data['Weather']=='Clear']

             Date/Time  Temp_C  ...  Press_kPa  Weather
67      1/3/2012 19:00   -16.9  ...     101.74    Clear
114     1/5/2012 18:00    -7.1  ...     100.71    Clear
115     1/5/2012 19:00    -9.2  ...     100.80    Clear
116     1/5/2012 20:00    -9.8  ...     100.83    Clear
117     1/5/2012 21:00    -9.0  ...     100.83    Clear
...                ...     ...  ...        ...      ...
8646   12/26/2012 6:00   -13.4  ...     102.47    Clear
8698  12/28/2012 10:00    -6.1  ...     101.27    Clear
8713   12/29/2012 1:00   -11.9  ...     101.31    Clear
8714   12/29/2012 2:00   -11.8  ...     101.33    Clear
8756  12/30/2012 20:00   -13.8  ...     101.52    Clear

[1326 rows x 8 columns]

In [ ]:
data[data['Weather']=='Clear'].count()

Date/Time           1326
Temp_C              1326
Dew Point Temp_C    1326
Rel Hum_%           1326
Wind Speed_km/h     1326
Visibility_km       1326
Press_kPa           1326
Weather             1326
dtype: int64

In [ ]:
#3 find the number of times when the windspeed was 4km/h
data.head(2)

       Date/Time  Temp_C  Dew Point Temp_C  ...  Visibility_km  Press_kPa  Weather
0  1/1/2012 0:00    -1.8              -3.9  ...            8.0     101.24      Fog
1  1/1/2012 1:00    -1.8              -3.7  ...            8.0     101.24      Fog

[2 rows x 8 columns]

In [ ]:
data['Wind Speed_km/h'].value_counts()

9     830
11    791
13    735
15    719
7     677
17    666
19    616
6     609
20    496
4     474
22    439
24    374
0     309
26    242
28    205
30    161
32    139
33     85
35     53
37     45
39     24
41     22
44     14
43     13
48     13
46     11
52      7
57      5
50      4
2       2
63      1
54      1
70      1
83      1
Name: Wind Speed_km/h, dtype: int64

In [ ]:
data[data['Wind Speed_km/h']==4]

             Date/Time  Temp_C  ...  Press_kPa       Weather
0        1/1/2012 0:00    -1.8  ...     101.24           Fog
1        1/1/2012 1:00    -1.8  ...     101.24           Fog
96       1/5/2012 0:00    -8.8  ...     100.32          Snow
101      1/5/2012 5:00    -7.0  ...     100.19          Snow
146      1/7/2012 2:00    -8.1  ...     100.15        Cloudy
...                ...     ...  ...        ...           ...
8768   12/31/2012 8:00    -8.6  ...     101.14  Snow Showers
8769   12/31/2012 9:00    -8.1  ...     101.09          Snow
8770  12/31/2012 10:00    -7.4  ...     101.05      Snow,Fog
8772  12/31/2012 12:00    -5.8  ...     100.78          Snow
8773  12/31/2012 13:00    -4.6  ...     100.63          Snow

[474 rows x 8 columns]

In [ ]:
#5 rename the weather column in the data set to weather condition
data['WeatherCondition']= data['Weather']
data.head(2)
data.drop(columns=['WeatherCondition'],axis=1,inplace=True)

In [ ]:
data.head()

       Date/Time  Temp_C  ...  Press_kPa               Weather
0  1/1/2012 0:00    -1.8  ...     101.24                   Fog
1  1/1/2012 1:00    -1.8  ...     101.24                   Fog
2  1/1/2012 2:00    -1.8  ...     101.26  Freezing Drizzle,Fog
3  1/1/2012 3:00    -1.5  ...     101.27  Freezing Drizzle,Fog
4  1/1/2012 4:00    -1.5  ...     101.23                   Fog

[5 rows x 8 columns]

In [ ]:
data.rename(columns={'Weather':'WeatherCondition'},inplace=True)

In [ ]:
#what is the mean visibility

In [ ]:
data.Visibility_km.mean()

27.66444672131151

In [ ]:
#What is the std deviation of the Pressure in this data

data.Press_kPa.std()

0.8440047459486474

In [ ]:
#what is the variance of relative humidity in the data

data['Rel Hum_%'].var()

286.2485501984998

In [ ]:
data[data['WeatherCondition']=='Snow']

             Date/Time  Temp_C  ...  Press_kPa  WeatherCondition
55       1/3/2012 7:00   -14.0  ...     100.95              Snow
84      1/4/2012 12:00   -13.7  ...     101.25              Snow
86      1/4/2012 14:00   -11.3  ...     100.97              Snow
87      1/4/2012 15:00   -10.2  ...     100.89              Snow
88      1/4/2012 16:00    -9.4  ...     100.79              Snow
...                ...     ...  ...        ...               ...
8779  12/31/2012 19:00     0.1  ...     100.13              Snow
8780  12/31/2012 20:00     0.2  ...     100.03              Snow
8781  12/31/2012 21:00    -0.5  ...      99.95              Snow
8782  12/31/2012 22:00    -0.2  ...      99.91              Snow
8783  12/31/2012 23:00     0.0  ...      99.89              Snow

[390 rows x 8 columns]

In [ ]:
#find all the instances where windspeed is above 24 and visibility is 25
data[(data['Wind Speed_km/h']==24)& (data['Visibility_km']==25)]

             Date/Time  Temp_C  ...  Press_kPa  WeatherCondition
43      1/2/2012 19:00    -4.8  ...     100.00     Mostly Cloudy
44      1/2/2012 20:00    -5.6  ...     100.07      Snow Showers
52       1/3/2012 4:00   -12.6  ...     100.68            Cloudy
66      1/3/2012 18:00   -16.3  ...     101.64      Mainly Clear
67      1/3/2012 19:00   -16.9  ...     101.74             Clear
...                ...     ...  ...        ...               ...
8658  12/26/2012 18:00   -10.0  ...     102.14            Cloudy
8663  12/26/2012 23:00    -9.7  ...     101.61            Cloudy
8706  12/28/2012 18:00    -9.0  ...     101.37      Mainly Clear
8754  12/30/2012 18:00   -12.6  ...     101.36      Mainly Clear
8756  12/30/2012 20:00   -13.8  ...     101.52             Clear

[107 rows x 8 columns]

In [ ]:
#find the mean value of each column against each weather condition

data.groupby('WeatherCondition').mean()

                                            Temp_C  ...   Press_kPa
WeatherCondition                                    ...
Clear                                     6.825716  ...  101.587443
Cloudy                                    7.970544  ...  100.911441
Drizzle                                   7.353659  ...  100.435366
Drizzle,Fog                               8.067500  ...  100.786625
Drizzle,Ice Pellets,Fog                   0.400000  ...  100.790000
Drizzle,Snow                              1.050000  ...  100.890000
Drizzle,Snow,Fog                          0.693333  ...   99.281333
Fog                                       4.303333  ...  101.184067
Freezing Drizzle                         -5.657143  ...  100.202857
Freezing Drizzle,Fog                     -2.533333  ...  100.441667
Freezing Drizzle,Haze                    -5.433333  ...  100.316667
Freezing Drizzle,Snow                    -5.109091  ...  100.520909
Freezing Fog                             -7.575000  ...  102.320000
Freezing Rain                            -3.885714  ...   99.647143
Freezing Rain,Fog                        -2.225000  ...   99.945000
Freezing Rain,Haze                       -4.900000  ...  100.375000
Freezing Rain,Ice Pellets,Fog            -2.600000  ...  100.950000
Freezing Rain,Snow Grains                -5.000000  ...   98.560000
Haze                                     -0.200000  ...  101.482500
Mainly Clear                             12.558927  ...  101.248832
Moderate Rain,Fog                         1.700000  ...   99.980000
Moderate Snow                            -5.525000  ...  100.275000
Moderate Snow,Blowing Snow               -5.450000  ...  100.570000
Mostly Cloudy                            10.574287  ...  101.025288
Rain                                      9.786275  ...  100.233333
Rain Showers                             13.722340  ...  100.404043
Rain Showers,Fog                         12.800000  ...   99.830000
Rain Showers,Snow Showers                 2.150000  ...  101.100000
Rain,Fog                                  8.273276  ...  100.500862
Rain,Haze                                 4.633333  ...  100.540000
Rain,Ice Pellets                          0.600000  ...  100.120000
Rain,Snow                                 1.055556  ...   99.951111
Rain,Snow Grains                          1.900000  ...  100.600000
Rain,Snow,Fog                             0.800000  ...  100.730000
Rain,Snow,Ice Pellets                     1.100000  ...  100.105000
Snow                                     -4.524103  ...  100.536103
Snow Pellets                              0.700000  ...   99.700000
Snow Showers                             -3.506667  ...  100.963500
Snow Showers,Fog                        -10.675000  ...  101.292500
Snow,Blowing Snow                        -5.410526  ...   99.704737
Snow,Fog                                 -5.075676  ...  100.688649
Snow,Haze                                -4.020000  ...  100.782000
Snow,Ice Pellets                         -1.883333  ...  100.548333
Thunderstorms                            24.150000  ...  100.230000
Thunderstorms,Heavy Rain Showers         10.900000  ...  100.260000
Thunderstorms,Moderate Rain Showers,Fog  19.600000  ...  100.010000
Thunderstorms,Rain                       20.433333  ...  100.420000
Thunderstorms,Rain Showers               20.037500  ...  100.233750
Thunderstorms,Rain Showers,Fog           21.600000  ...  100.063333
Thunderstorms,Rain,Fog                   20.600000  ...  100.080000

[50 rows x 6 columns]

In [ ]:
#What is the min and max value of each column against each weather condition

data.groupby('WeatherCondition').agg(['min','max'])

                                                Date/Time  ... Press_kPa
                                                      min  ...       max
WeatherCondition                                           ...
Clear                                      1/11/2012 1:00  ...    103.63
Cloudy                                     1/1/2012 17:00  ...    103.65
Drizzle                                   1/23/2012 21:00  ...    101.56
Drizzle,Fog                               1/23/2012 20:00  ...    102.07
Drizzle,Ice Pellets,Fog                   12/17/2012 9:00  ...    100.79
Drizzle,Snow                             12/17/2012 15:00  ...    101.15
Drizzle,Snow,Fog                         12/18/2012 21:00  ...    100.15
Fog                                         1/1/2012 0:00  ...    103.04
Freezing Drizzle                          1/13/2012 10:00  ...    101.02
Freezing Drizzle,Fog                        1/1/2012 2:00  ...    101.27
Freezing Drizzle,Haze                      2/1/2012 11:00  ...    100.36
Freezing Drizzle,Snow                      1/13/2012 3:00  ...    101.18
Freezing Fog                               1/22/2012 6:00  ...    102.85
Freezing Rain                             1/13/2012 11:00  ...    101.00
Freezing Rain,Fog                         1/17/2012 23:00  ...    101.01
Freezing Rain,Haze                         2/1/2012 14:00  ...    100.41
Freezing Rain,Ice Pellets,Fog             12/17/2012 3:00  ...    100.95
Freezing Rain,Snow Grains                  1/13/2012 9:00  ...     98.56
Haze                                      1/22/2012 12:00  ...    102.97
Mainly Clear                              1/10/2012 11:00  ...    103.59
Moderate Rain,Fog                         12/10/2012 8:00  ...     99.98
Moderate Snow                             1/12/2012 15:00  ...    100.67
Moderate Snow,Blowing Snow               12/27/2012 10:00  ...    100.64
Mostly Cloudy                              1/1/2012 16:00  ...    103.65
Rain                                       1/1/2012 18:00  ...    102.26
Rain Showers                               1/1/2012 22:00  ...    102.31
Rain Showers,Fog                          10/20/2012 3:00  ...     99.83
Rain Showers,Snow Showers                  11/4/2012 8:00  ...    101.11
Rain,Fog                                  1/23/2012 18:00  ...    101.77
Rain,Haze                                  3/13/2012 7:00  ...    100.61
Rain,Ice Pellets                          12/18/2012 5:00  ...    100.12
Rain,Snow                                  1/10/2012 5:00  ...    101.07
Rain,Snow Grains                          12/21/2012 0:00  ...    100.60
Rain,Snow,Fog                             12/8/2012 21:00  ...    100.73
Rain,Snow,Ice Pellets                     12/21/2012 1:00  ...    100.47
Snow                                       1/10/2012 1:00  ...    102.73
Snow Pellets                             11/24/2012 15:00  ...     99.70
Snow Showers                               1/12/2012 7:00  ...    102.50
Snow Showers,Fog                          12/26/2012 9:00  ...    102.52
Snow,Blowing Snow                         1/13/2012 21:00  ...    100.62
Snow,Fog                                 12/16/2012 15:00  ...    102.07
Snow,Haze                                  2/1/2012 17:00  ...    100.99
Snow,Ice Pellets                          12/10/2012 3:00  ...    100.96
Thunderstorms                              7/16/2012 1:00  ...    100.62
Thunderstorms,Heavy Rain Showers           5/29/2012 6:00  ...    100.26
Thunderstorms,Moderate Rain Showers,Fog    7/17/2012 6:00  ...    100.01
Thunderstorms,Rain                        5/25/2012 20:00  ...    100.83
Thunderstorms,Rain Showers                5/29/2012 16:00  ...    101.06
Thunderstorms,Rain Showers,Fog             6/29/2012 3:00  ...    100.64
Thunderstorms,Rain,Fog                     7/17/2012 5:00  ...    100.08

[50 rows x 14 columns]

In [ ]:
#show all the records where weather is Fog

data[data.WeatherCondition=='Fog']

             Date/Time  Temp_C  ...  Press_kPa  WeatherCondition
0        1/1/2012 0:00    -1.8  ...     101.24               Fog
1        1/1/2012 1:00    -1.8  ...     101.24               Fog
4        1/1/2012 4:00    -1.5  ...     101.23               Fog
5        1/1/2012 5:00    -1.4  ...     101.27               Fog
6        1/1/2012 6:00    -1.5  ...     101.29               Fog
...                ...     ...  ...        ...               ...
8716   12/29/2012 4:00   -16.0  ...     101.25               Fog
8717   12/29/2012 5:00   -14.8  ...     101.25               Fog
8718   12/29/2012 6:00   -13.8  ...     101.25               Fog
8719   12/29/2012 7:00   -14.8  ...     101.22               Fog
8722  12/29/2012 10:00   -12.0  ...     101.15               Fog

[150 rows x 8 columns]

In [ ]:
#find all the instances where the weather condition is clear or visibility is above 40

data[(data.WeatherCondition=='Clear')|(data.Visibility_km>40)]

             Date/Time  Temp_C  ...  Press_kPa  WeatherCondition
67      1/3/2012 19:00   -16.9  ...     101.74             Clear
106     1/5/2012 10:00    -6.0  ...     100.45      Mainly Clear
107     1/5/2012 11:00    -5.6  ...     100.41      Mainly Clear
108     1/5/2012 12:00    -4.7  ...     100.38      Mainly Clear
109     1/5/2012 13:00    -4.4  ...     100.40      Mainly Clear
...                ...     ...  ...        ...               ...
8749  12/30/2012 13:00   -12.4  ...     100.92     Mostly Cloudy
8750  12/30/2012 14:00   -11.8  ...     100.96      Mainly Clear
8751  12/30/2012 15:00   -11.3  ...     101.05      Mainly Clear
8752  12/30/2012 16:00   -11.4  ...     101.15      Mainly Clear
8756  12/30/2012 20:00   -13.8  ...     101.52             Clear

[3027 rows x 8 columns]